# The URL the site will be built for
base_url = "https://chronal.space"

title = "Anuj's Blog"
default_language = "en" 

theme = "Zulma"

highlight_code = true
highlight_theme = "base16-ocean-dark"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_rss = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", paginate_by = 10, rss = true},
]

build_search_index = true

[extra]
zulma_themes = ["default", "darkly", "flatly", "pulse", "simplex", "lux", "slate", "solar", "superhero"]

zulma_menu = [
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

zulma_brand = {text = "Home"}
zulma_title = "Anuj's Blog"
zulma_theme = "darkly"
zulma_allow_theme_selection = true

[search]
include_title = true
include_description = false
include_content = true
